# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmod',
            name='guid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
