# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drink',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='guid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
